### ISSUE TITLE
Adapting the code for a different probe than Neuropixels 

### ISSUE THREAD

**Issue by elladulko** [petersaj/AP_histology#15]
Hi! I would like to run this code for UCLA and Cambridge Neurotech probes. Both are shorter than Neuropixels, so the probe length and targeted structures are not accurate. Do you possibly know where in the code you specify the length of the shanks? 
I would appreciate it! 
Ela 
Graduate Student

**Comment by petersaj** [comment]
Hi Ela - are talking about using `AP_get_probe_histology`? That doesn't actually use any information about the length of the probe, the output in `probe_ccf.mat` instead stores: 
1) the CCF points you identified the probe tract on
2) the coordinates and associated areas for a straight line on that trajectory through the whole brain. 

If we could confidently mark the endpoint of the probe in histology, then we could use the length of the probe to get the position in CCF of our recording sites. With Neuropixels though, usually the endpoint can't be accurately determined since there's no physical damage and the dye may or may not have given the tip location. So instead, this stores the areas/location of the trajectory as a line through the whole brain, then the location of the probe along that trajectory is gotten with electrophysiological landmarks. 

This means that any step that uses the length of the probe would happen after `AP_get_probe_histology` and would be specific to your pipeline. Happy to help suggest things with more info about your data or clarify what I mean if that didn't make sense?

**Comment by Virginia9733** [comment]
Hey Andy, thank you for the suggestions. 
Could you please kindly show me more details about how to adjust the probe length after AP_get_probe_histology?
Sometimes before launching a ephys recording, I will plan the trajectory and check the position using fibers instead of real probes. In that cases, I don't have ephys data for further mapping, and the trajectory alone the whole straight line sometimes would be a bit misleading.

I have a following up question. I am using AP_histology not only to track neuropixels trajectory (including 1 shank and 4 shanks), but also tetrodes lesions tracks, usually just dots on the tissue burned by electricity, as shown below. In this case, the ephys mapping part might be complicated, since only the tip of the tetrodes supposes to have ephys recording. Do you have any suggestions regarding this part?

Many thanks!
![Screenshot 2023-03-12 202934](https://user-images.githubusercontent.com/61534754/224541675-88234707-c69b-4ea3-ba7e-665a1c9eb27d.png)
![TT7-2](https://user-images.githubusercontent.com/61534754/224541758-3262a2ae-abea-43b6-999b-63ef9140ef7f.png)

**Comment by petersaj** [comment]
I don't really understand your question: do you mean you do fiber implants to try out a trajectory before using a Neuropixels probe? What information are you getting, and what would you like? 

If you're talking about planning rather than an actual experiment, just in case you don't know about my Neuropixels Trajectory Explorer for planning experiments, here's that: https://github.com/petersaj/neuropixels_trajectory_explorer

I'm also not sure what you're asking in your second question - if you have precise recording locations from electrolytic lesions, what other information are you looking to get? If your experiment involves slowly descending the probe over days, and your thought is that you'd like the whole trajectory, could you not paint the tetrode with dye the same way you'd paint a Neuropixels probe?
