### ISSUE TITLE
The step of White-balance slides was not performed

### ISSUE THREAD

**Issue by Tan-Lao** [petersaj/AP_histology#24]
Hi, Professor Peter.I tried your demo_histology_pipline code, and the slice format is the same as in your video, which is a tiff file and has RGB channels, but when I run it to the AP_process_histology function, I'm just going to extract individual slices, and I'm not going to set the white balance.

Levi
PhD Student

**Comment by petersaj** [comment]
Hi Levi - is the tiff file actually RGB with values 0-255, or does it have separate gray-scale channels for each color? It sounds like it may be RGB, since the pipeline doesn't set white balance on RGB images. I don't remember exactly why I did that - I think it was because RGB images are typically already properly white-balanced since their range is so small. If you're possibly able to send me a sample image, I can have a look at adding in white balance for RGB?

**Comment by Tan-Lao** [comment]
Hi, Professor Peter. Thank you very much for your reply.  I am also aware of this, as you said, the image is RGB, and then the white balance will not be set, I feel like this has no problem for the subsequent processing.
I've already fitted the 3D brain. Now there is only one last step: Align histology with electrophysiology.  I have some problems, just like other people, I also use SpikeGLX to collect data.  So I am currently trying to use alignatlasdata from Enny van Beest.

**Comment by petersaj** [comment]
It sounds like you don't have any questions for me in that case, I'll close this issue for now but feel free to open it again if something comes up.
