### ISSUE TITLE
Identifying probe trace when it is across multiple slices

### ISSUE THREAD

**Issue by cspurandare** [petersaj/AP_histology#26]
Hi,
I have just started using your histology pipeline and everything seems good and easy to use. I am encountering an issue where my probe did not end up in a single slice, but instead it traversed different depths in different (anterior to posterior) slices. The 8 slices are attached. I am at the step "AP_get_probe_histology", but 
[2 (4 files merged).pdf](https://github.com/petersaj/AP_histology/files/12114788/2.4.files.merged.pdf)
I am not sure if there is a way to assign probe track if it extends across multiple slices? As I understand it, the draw probe utility expects me to draw a line, but I dont know if it can stitch together different lines (or points) across different slices.
Thanks and looking forward to your reply !
Chinmay

**Comment by petersaj** [comment]
Hi Chinmay - right that probe tracts almost never exist in just one slice: you mark the section of the probe visible on each slice by pressing the number corresponding to the probe (e.g. `1`), then the final probe location is the line of best fit between all your marked points across all slices. 

Apologies the documentation for this isn't great, I'm hoping to update it in the near future since I'm just getting back into histology processing
