### ISSUE TITLE
Integrating AP_histology with IBL

### ISSUE THREAD

**Issue by jel0624** [petersaj/AP_histology#35]
Dear Andrew, 

Thank you so much for this amazing tool. I was just wondering if there is a way to use the results obtained from **AP_histology** to use **IBL Ephys Alignment tool**. I know you mentioned the **AP_align_probe_histology** function that is part of this repository but I was wondering if you have tried integrating this repo with the IBL tool. Thanks!

**Comment by jel0624** [comment]
Cool! Thanks for the pointer.
Also, I've been trying the AP_align_probe_histology given that it's in the same repo.
I keep getting an error when it tries to access the probe boundaries area:
![Screenshot 2024-09-28 105851](https://github.com/user-attachments/assets/bb85aa99-f7f4-44b5-b64b-277bf13d4cb2)
it seems like it in `trajectory_area_boundary_idx = [1;find(diff(double(probe_ccf(use_probe).trajectory_areas)) ~= 0)+1];`, probe_ccf(use_probe).trajectory_areas is a table, but it is trying to convert into double. Perhaps there should be a column entry. Do you know which column I should add? or is there something I'm missing?

**Comment by petersaj** [comment]
Right - turns out that that only worked with old versions of the code, so that won't work without a bunch of updates. 

I've looked into making a new GUI for this today, but looks like it'll be a bit more involved than I expected, and I also wouldn't trust the alignment just through firing rate and multiunit correlation. 

I have an issue flagged about this (https://github.com/petersaj/AP_histology/issues/29) and I updated the links to other tools, hopefully I'll be able to add this feature in the near-ish future.

 I'll close this issue for now, but let me know if there's something else I can help with.
